Test du login et createUser
ecoleduweb/ProjetApplicationH2024 pull request #15
Opened 2024-02-19 22:33 UTC by PhilippeSaucier

2024-02-19 22:35 UTC, Zacha21 approved these changes
Ca me semble bien

2024-02-23 20:28 UTC, antoineCegepRDL requested changes
Pleins de petits commentaires. Tu pourrais en prendre certains et ouvrir des tickets et les ajouter dans le backlog pour qu'ils soient réalisés par quelqu'un d'autre. Pour les commentaires, c'est assez simple à faire ;).

2024-02-23 20:28 UTC, antoineCegepRDL commented on back-end/API/app/__init__.py
> +
Peux-tu ajouter un throw error si jamais le dev n'a pas mis d'url vers la BD dans son fichier .env svp?

2024-02-23 20:28 UTC, antoineCegepRDL commented on back-end/API/app/__init__.py
> +    from app.controllers.user_controller import app_blueprint
Peut-etre un petit commentaire pour dire ça fait quoi? (Évite l'importation circulaire)

2024-02-23 20:28 UTC, antoineCegepRDL commented on back-end/API/app/__init__.py
> +    if any("pytest" in arg for arg in sys.argv):
Nécessaire?

2024-02-23 20:28 UTC, antoineCegepRDL commented on back-end/API/app/controllers/user_controller.py
>  def createUser():
Ajouter un TODO dans la méthode pour dire qu'elle n'est pas terminée.

2024-02-23 20:28 UTC, antoineCegepRDL commented on back-end/API/app/controllers/user_controller.py
>          return jsonify({'message': 'Missing required fields'}), 400
Ça fonctionne? J'ai pas l'impression. Ajouter TODO pour dire que ce n'est pas complet.

2024-02-23 20:28 UTC, antoineCegepRDL commented on back-end/API/app/controllers/user_controller.py
>      return user_service.getAllUsers()
Valider si l'utilisateur est un admin pour retourner toute la liste. (à mettre dans un TODO)

2024-02-23 20:28 UTC, antoineCegepRDL commented on back-end/API/app/repositories/user_repo.py
Je te propose de nommer cette classe AuthenticationService. UserRepo sera plus en lien avec la bd, le token, c'est un service qui le fournit.

2024-02-23 20:28 UTC, antoineCegepRDL commented on back-end/API/requirements.txt
> +SQLAlchemy==2.0.25
tout est là? dotenv mettons? Sinon c'est good!

2024-02-23 20:28 UTC, antoineCegepRDL commented on back-end/API/tests/test_user.py
> +    assert response.status_code == 200
Il faudra ajouter le user dans la bd avec son mdp pour que le test fonctionne. Je te propose de rouler les migrations avant les tests pour qu'ils fonctionnent et y ajouter le user Phil dans la bd automatiquement pour que les tests soient toujours fonctionnels si jamais on changeait de serveur!

2024-02-26 13:32 UTC, PhilippeSaucier commented on back-end/API/app/__init__.py
> +    if any("pytest" in arg for arg in sys.argv):
N'était pas nécessaire, je l'ai enlevé

2024-02-26 13:38 UTC, PhilippeSaucier commented on back-end/API/app/controllers/user_controller.py
>          return jsonify({'message': 'Missing required fields'}), 400
Modification apportées

2024-02-26 13:40 UTC, PhilippeSaucier commented on back-end/API/app/controllers/user_controller.py
>      return user_service.getAllUsers()
TODO fait

2024-02-26 13:41 UTC, PhilippeSaucier commented on back-end/API/app/repositories/user_repo.py
Renommé

2024-02-26 13:43 UTC, PhilippeSaucier commented on back-end/API/requirements.txt
> +SQLAlchemy==2.0.25
Modifié

2024-02-26 14:12 UTC, PhilippeSaucier commented on back-end/API/app/repositories/user_repo.py
Modifications faites

2024-02-26 14:16 UTC, PhilippeSaucier commented on back-end/API/app/controllers/user_controller.py
>  def createUser():
Fait

2024-02-26 14:44 UTC, closed without merging