update readme
ecoleduweb/ProjetApplicationH2024 pull request #4
Opened 2024-02-05 20:53 UTC by Flutz17

2024-02-05 22:58 UTC, antoineCegepRDL requested changes

2024-02-05 22:58 UTC, antoineCegepRDL commented on README.md
> +CREATE DATABASE todo;
Retirer cette partie svp

2024-02-05 22:58 UTC, antoineCegepRDL commented on README.md
> +```
Je ne crois pas ce que soit utile non plus.

2024-02-05 22:58 UTC, antoineCegepRDL commented on README.md
> +```bash
Ajoute la ligne pour rouler les migrations avant ici svp

2024-02-12 14:34 UTC, antoineCegepRDL approved these changes

2024-02-12 19:10 UTC, CAFortier approved these changes

2024-02-12 19:10 UTC, merged