Updated requiment.txt
ecoleduweb/ProjetApplicationH2024 pull request #70
Opened 2024-03-25 20:50 UTC by antoineCegepRDL

S'assurer que le contenu du fichier contient tout ce qu'il faut! (coucou Samuel qui va déployer en prod!)

2024-03-25 20:53 UTC, CAFortier approved these changes

2024-04-15 17:21 UTC, Zacha21 approved these changes

2024-04-15 18:15 UTC, Zacha21 submitted a review, later dismissed
Beau ménage !

2024-04-15 18:17 UTC, CAFortier submitted a review, later dismissed

2024-04-15 18:22 UTC, SamDumont requested changes
Il faudrait vérifier l'utilitée de mysqlclient=2.2.1, car aux dernières nouvelles, les serveurs ne le trouvaient pas et cela empêchait le déploiment de bien fonctionner.

2024-04-15 18:57 UTC, SamDumont approved these changes
La modification apportée est correcte

2024-04-15 19:56 UTC, merged