Ajout des Tests Playwright FE
ecoleduweb/ProjetApplicationH2024 pull request #8
Opened 2024-02-12 20:28 UTC by RinoGamache

Voici les tests seulement coté front-end (Remplis les formulaire de login, register, et mot de passe oublié...)

2024-02-19 15:48 UTC, antoineCegepRDL requested changes

2024-02-19 15:48 UTC, antoineCegepRDL commented on qa-test/README.md
> +# 🎭 Playwright
Tu pourrais mettre un readme pour notre projet. Commment ça marche, ce qu'il faut faire etc... bref, ça être la documentation.

2024-02-19 15:48 UTC, antoineCegepRDL commented on qa-test/tests/test.login.spec.ts
> +  // MANQUE LA VALIDATION AVEC API... A faire
Tu pourrais ajouter un test qui valide que les messages d'erreurs sont affichés quand le mot de passe et le courriel sont absents mettons??

2024-02-19 15:48 UTC, antoineCegepRDL commented on qa-test/.github/workflows/playwright.yml
> +name: Playwright Tests
Normal qu'il y aie deux .github?

2024-02-19 18:45 UTC, RinoGamache commented on qa-test/.github/workflows/playwright.yml
> +name: Playwright Tests
Non

2024-02-19 18:48 UTC, RinoGamache commented on qa-test/.github/workflows/playwright.yml
> +name: Playwright Tests
Suppression fait

2024-02-19 18:51 UTC, RinoGamache commented on qa-test/tests/test.login.spec.ts
> +  // MANQUE LA VALIDATION AVEC API... A faire
Je me lance là dessus au courant de l'après-midi

2024-02-26 13:28 UTC, RinoGamache commented on qa-test/tests/test.login.spec.ts
> +  // MANQUE LA VALIDATION AVEC API... A faire
On va dire que ce message s'addresse à ce matin finalement :P

2024-03-11 13:24 UTC, RinoGamache commented on qa-test/tests/test.login.spec.ts
> +  // MANQUE LA VALIDATION AVEC API... A faire
j'ai modifié les test pour vérifier le message d'erreurs (si applicables) avec le YUM
Pour le moment register n'a pas le YUM, donc je le laisse avec les messages d'erreurs de validation de base...

2024-03-11 13:40 UTC, RinoGamache commented on qa-test/README.md
> +# 🎭 Playwright
J'ai légèrement modifié la doc du readme

2024-03-18 12:46 UTC, FelixBeauX54 approved these changes
Bien beau capitaine

2024-03-18 12:47 UTC, Zacha21 approved these changes
Beaucoup de codes en commentaires sinon ca semble bien

2024-03-18 14:09 UTC, antoineCegepRDL approved these changes

2024-03-18 14:10 UTC, merged