Position du footer / Villes et villages dans le select / Console.log supprimé
ecoleduweb/ProjetApplicationH2024 pull request #83
Opened 2024-04-08 01:31 UTC by CAFortier

2024-04-08 19:55 UTC, antoineCegepRDL requested changes

2024-04-08 19:55 UTC, antoineCegepRDL commented on .github/workflows/deploy-DEV.yml
> -            echo PUBLIC_BASE_URL = ${{ secrets.FRONT_PUBLIC_URL }} >> .env
Ne pas modifier ces fichiers

2024-04-15 17:28 UTC, Zacha21 approved these changes
Ca semble bien

2024-04-15 17:54 UTC, WillD5 approved these changes
Lookin' good

2024-04-15 18:19 UTC, merged